services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: playtopay
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: paras2724
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5

  backend:
    build: .
    environment:
      DB_NAME: playtopay
      DB_USER: postgres
      DB_PASSWORD: paras2724
      DB_HOST: db
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery:
    build: .
    command: celery -A PlaytoPayout worker --loglevel=info
    environment:
      DB_NAME: playtopay
      DB_USER: postgres
      DB_PASSWORD: paras2724
      DB_HOST: db
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery-beat:
    build: .
    command: celery -A PlaytoPayout beat --loglevel=info
    environment:
      DB_NAME: playtopay
      DB_USER: postgres
      DB_PASSWORD: paras2724
      DB_HOST: db
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:
