# Generated by Django 6.0.4 on 2026-04-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payout',
            name='bank_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
