# Generated by Django 6.0.4 on 2026-04-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        ('payouts', '0002_payout_attempts_payout_bank_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idempotantkey',
            name='key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='idempotantkey',
            unique_together={('merchant', 'key')},
        ),
    ]
